version: "3.8"

services:

  postgres:
    container_name: postgres-bot
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis-bot
    image: redis:5-alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis-data:/data

  exchange-platform:
    container_name: exchange-platform-bot
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  redis-data:
